### ISSUE TITLE
Redemption widget

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/core-components#461]

**Comment by sukrita3** [comment]
Figma File
[https://www.figma.com/file/qZ7Asm9lG4NST4HcQzsDtv/BOSON-x-DeepWork-Prototype-(Metaverse-%2B-Redemption-Widgets)?node-id=9401-61347&t=owU5ytMDcvRBLLHd-0](url)

**Comment by sukrita3** [comment]
Figma currently shows a link in the Exchange tile to view delivery status. As we do not have this, let's use the experience on exchanges that is currently implemented in the dApp
**Figma:** 

![Image](https://user-images.githubusercontent.com/122606799/229104708-d6de4974-079d-47c4-b93a-e136169fb98b.png)


**dApp / Implementation Experience:**

![Image](https://user-images.githubusercontent.com/122606799/229104779-bff6130f-e39e-4c32-b4c4-03af7cb2c8e8.png)

**Comment by sukrita3** [comment]
When you click on an exchange, it should take you to the PDP (in this experience within the modal), with the most recent exchange state. 


![Image](https://user-images.githubusercontent.com/122606799/229105725-04801c90-8164-4987-9b2d-4ad951ba1bb4.png)

**Comment by sukrita3** [comment]
For the Cancel page, could we use the experience that is there in the dApp?


![Image](https://user-images.githubusercontent.com/122606799/229109583-f589bf11-f12e-4344-b610-2de8461ac899.png)



![Image](https://user-images.githubusercontent.com/122606799/229109609-fefdbabb-6197-43a1-9154-b29c51c1289e.png)

**Comment by sukrita3** [comment]
FYI, in the dApp, there is no filter available for the Buyer on exchanges. It looks like it defaults to showing Committed first, followed by Redeemed, and then Cancelled. 



![Image](https://user-images.githubusercontent.com/122606799/229110175-1f0ef5e9-77bd-42c4-82c1-f1170e30e79e.png)

**Comment by albertfolch-redeemeum** [comment]
TODO: apply logic of optional/mandatory email input in the redeemption form (context: https://github.com/bosonprotocol/interface/issues/605)
