### ISSUE TITLE
Commit widget minor issues

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/core-components#653]

**Comment by sukrita3** [comment]
![Screenshot 2024-01-26 at 14 09 20](https://github.com/bosonprotocol/core-components/assets/122606799/0dcb261a-78f9-448e-adc7-aac174bafb1a)

**Comment by sukrita3** [comment]
![Screenshot 2024-01-26 at 14 04 52](https://github.com/bosonprotocol/core-components/assets/122606799/60bdee87-85ba-46c4-9c92-ea0654241905)

**Comment by sukrita3** [comment]
![Screenshot 2024-01-26 at 14 01 09](https://github.com/bosonprotocol/core-components/assets/122606799/6111dce0-cdfc-4b66-a60f-d3e9eca510b3)

**Comment by sukrita3** [comment]
![Screenshot 2024-01-26 at 13 59 21](https://github.com/bosonprotocol/core-components/assets/122606799/e0cc3a12-dd37-4cb8-a139-dff4ef2b9ef9)

**Comment by sukrita3** [comment]
![Screenshot 2024-01-26 at 13 47 47](https://github.com/bosonprotocol/core-components/assets/122606799/b5ec4a94-d573-46a6-97ee-71414def0107)

**Comment by sukrita3** [comment]
@albertfolch-redeemeum couldn't see some of these fixed, so let's discuss tomorrow

**Comment by sukrita3** [comment]
I am not sure why we have the Boson logo here?


![Image](https://github.com/bosonprotocol/core-components/assets/122606799/38f97511-fe60-4fde-8641-09e779ec8e8d)

**Comment by sukrita3** [comment]
![Image](https://github.com/bosonprotocol/core-components/assets/122606799/11de2a14-3f6a-43d5-a984-36a7b490569f)

**Comment by sukrita3** [comment]
Looking at Figma, think we wanted the Redeemable from date (and other dates to be) in format 11 Jan. 2024 (not all numerical as shown)


![Image](https://github.com/bosonprotocol/core-components/assets/122606799/4b68a4a4-de0b-4669-80ff-d159129eef91)
